dashboard/urls.py
from django.urls import path,include
from . import views


app_name = 'dashboard'

urlpatterns =[
    path('',views.DashboardHomeView.as_view(),name = 'index'),

    #Company
    path('companies',views.CompanyListView.as_view(),name = 'companies-list'),
    path('companies/create',views.CompanyCreateView.as_view(),name = 'companies-create'),
    path('companies/<int:pk>/update',views.CompanyUpdateView.as_view(), name = 'companies-update'),
    path('companies/<int:pk>/delete/',views.CompanyDeleteView.as_view(), name = 'companies-delete'), 
    path('companies/<int:pk>/detail/',views.CompanyDetailView.as_view(), name = 'companies-detail'),

    #Product 
    path('products',views.ProductListView.as_view(), name = 'products-list'),
    path('products/create',views.ProductCreateView.as_view(),name = 'products-create'),
    path('products/<int:pk>/update',views.ProductUpdateView.as_view(), name = 'products-update'),
    path('products/<int:pk>/delete/',views.ProductDeleteView.as_view(), name = 'products-delete'), 
    path('products/<int:pk>/detail/',views.ProductDetailView.as_view(), name = 'products-detail'),
    
    #Order
    path('orders',views.OrderListView.as_view(), name = 'orders-list'),
    path('orders/create',views.OrderCreateView.as_view(),name = 'orders-create'),
    path('orders/<int:pk>/update',views.OrderUpdateView.as_view(), name = 'orders-update'),
    path('orders/<int:pk>/delete/',views.OrderDeleteView.as_view(), name = 'orders-delete'), 
    path('orders/<int:pk>/detail/',views.OrderDetailView.as_view(), name = 'orders-detail'),
]

dms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
]
#Media Url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.
#Company Models
class Company(models.Model):
    name = models.CharField(max_length = 50)

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        ordering = ('id',)

    def __str__(self):
        return self.name
        

#Product Models
class Product(models.Model):
    name = models.CharField(max_length = 50)
    selling_price = models.IntegerField()
    cost_price = models.IntegerField()
    quantity_stock = models.CharField(max_length = 50)
    product_image = models.ImageField(upload_to = 'products/',blank=True,null=True)
    mfg_date = models.DateField()
    expired_date =models.DateField()
    company = models.ForeignKey(Company, on_delete = models.CASCADE, related_name='products')

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('id',)

    def __str__(self):
        return self.name

#Order Models
class Order(models.Model):
    name = models.CharField(max_length = 50)
    address = models.CharField(max_length = 100)
    phone = models.CharField(max_length = 10)
    product = models.ForeignKey(Product, on_delete = models.CASCADE, related_name='orders')
    company = models.ForeignKey(Company,on_delete = models.CASCADE, related_name='orders')
    quantity_order = models.CharField(max_length = 50)
    is_order = models.BooleanField(default = True)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'
        ordering = ('id',)

    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms

from . models import *

class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = ['name',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                }
            )

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = []

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = []
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {
                    'class' : 'form-control',
                }
            )

dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,CreateView,UpdateView,DeleteView,DetailView
from django.urls import reverse_lazy

# Create your views here.
from . models import *
from . forms import *

class DashboardHomeView(TemplateView):
    template_name= "dashboard/index.html"

#Company view
class CompanyListView(ListView):
    template_name = 'dashboard/companies/list.html'
    model = Company


class CompanyCreateView(CreateView):
    template_name = 'dashboard/companies/form.html'
    form_class = CompanyForm
    success_url = reverse_lazy('dashboard:companies-list')


class CompanyUpdateView(UpdateView):
    template_name = 'dashboard/companies/form.html'
    form_class = CompanyForm
    model = Company
    success_url = reverse_lazy('dashboard:companies-list')


class CompanyDeleteView(DeleteView):
    model = Company
    success_url = reverse_lazy('dashboard:companies-list')


class CompanyDetailView(DetailView):
    template_name = 'dashboard/companies/form.html'
    model = Company

#Product View
class ProductListView(ListView):
    template_name = 'dashboard/products/list.html'
    model = Product


class ProductCreateView(CreateView):
    template_name = 'dashboard/products/form.html'
    form_class = ProductForm
    success_url = reverse_lazy('dashboard:products-list')

class ProductUpdateView(UpdateView):
    template_name = 'dashboard/products/form.html'
    form_class = ProductForm
    model = Product
    success_url = reverse_lazy('dashboard:products-list')

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('dashboard:products-list')

class ProductDetailView(DetailView):
    template_name = 'dashboard/products/form.html'
    model = Product

#order view
class OrderListView(ListView):
    template_name = 'dashboard/orders/list.html'
    model = Order


class OrderCreateView(CreateView):
    template_name = 'dashboard/orders/form.html'
    form_class = OrderForm
    success_url = reverse_lazy('dashboard:orders-list')

class OrderUpdateView(UpdateView):
    template_name = 'dashboard/orders/form.html'
    form_class = OrderForm
    model = Order
    success_url = reverse_lazy('dashboard:orders-list')

class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('dashboard:orders-list')

class OrderDetailView(DetailView):
    template_name = 'dashboard/orders/form.html'
    model = Order

home/views.py
from django.shortcuts import render

# Create your views here.

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="/static/dashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/static/dashboard/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-dark bg-dark sidebar sidebar-dark accordion" id="accordionSidebar" >

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">DMS Admin </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active" style="list-style:none">
                <a class="nav-link" href="{% url 'dashboard:index' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                DMS
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item" style="list-style:none">
            <a class="nav-link " href="{% url 'dashboard:companies-list' %}" 
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Company</span>
                </a>
            </li>
             <li class="nav-item" style="list-style:none">
                <a class="nav-link " href="{% url 'dashboard:products-list' %}" 
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Product</span>
                </a>
            </li>
            <li class="nav-item" style="list-style:none">
                <a class="nav-link " href="{% url 'dashboard:orders-list' %}" 
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Order</span>
                </a>
            </li>  
            <li class="nav-item" style="list-style:none">
                <a class="nav-link " href="#" data-toggle="modal" data-target="#logoutModal"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    <span>Logout</span>
                </a>
            </li>       

            <!-- Divider -->
            <hr class="sidebar-divider">

          

        </ul>
        <!-- End of Sidebar -->

         <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="/dashboard/accounts/logout">Logout</a>
            </div>
        </div>
    </div>
</div>
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
           
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block main %}

                    {% endblock main %}
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="#">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/static/dashboard/vendor/jquery/jquery.min.js"></script>
    <script src="/static/dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/dashboard/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/static/dashboard/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/dashboard/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/static/dashboard/js/demo/datatables-demo.js"></script>
    <!-- //delete link script with modal popup -->
    <script>
        $('body').on('click','.delete-link',function(e){
            if(! confirm("are you sure you want to delete ? "))
                e.preventDefault();
        }
        );
    </script>
    {% block script %}


    {% endblock script %}
</body>

</html>

dashboard/templates/dashboard/companies/form.html
{% extends 'dashboard/base.html' %}

{% block main %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Company</h6>
        </div>
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label >{{field.label}}{% if field.field.required %} * {% endif %} </label>
                    {{ field }}
                    <span class="form-error-text">{{ field.errors|striptags|safe }}</span>
                </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock main %}

dashboard/templates/dashboard/companies/list.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
               
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Company</h6>
                        <div class="float-right">
                            <a href="{% url 'dashboard:companies-create' %}" class = "btn btn-primary">
                                <i class="fa fa-plus"></i>&nbsp; Add Company
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Name</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for object in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ object.name }}</td>
                                       <td>
                                        <div class="btn-group" role="group">
                                           <a href="{% url 'dashboard:companies-update' object.pk %}" class="btn btn-info btn-sm">
                                            <i class="fas fa-pen"></i>
                                           </a> 
                                           {% if not object.non_deletetable %}
                                           <form action="{% url 'dashboard:companies-delete' object.pk %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-danger btn-sm delete-link ml-2" data-tooltip="tooltip" title="Delete">
                                                <e class="far fa-trash-alt"></e>
                                            </button>
                                           </form>
                                           {% endif %}
                                        </div>
                                       </td>

                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{% endblock main %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <h1>Welcome to Dashboard</h1>

{% endblock main %}

{% block script %}

            

{% endblock script %}

dashboard/templates/dashboard/orders/form.html
{% extends 'dashboard/base.html' %}

{% block main %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Product</h6>
        </div>
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label >{{field.label}}{% if field.field.required %} * {% endif %} </label>
                    {{ field }}
                    <span class="form-error-text">{{ field.errors|striptags|safe }}</span>
                </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock main %}

dashboard/templates/dashboard/orders/list.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
               
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Order</h6>
                        
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Phone Number</th>
                                        <th>Product</th>
                                        <th>Company</th>
                                        <th>Quantity order</th>
                                        <th>Is Order</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for object in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ object.name }}</td>
                                        <td>{{ object.address }}</td>
                                        <td>{{ object.phone }}</td>
                                        <td>{{ object.product }}</td>
                                        <td>{{ object.company }}</td>
                                        <td>{{ object.quantity_order }}</td>
                                        <td>{{ object.is_order }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                               <a href="{% url 'dashboard:orders-update' object.pk %}" class="btn btn-info btn-sm">
                                                <i class="fas fa-pen"></i>
                                               </a> 
                                               {% if not object.non_deletetable %}
                                               <form action="{% url 'dashboard:orders-delete' object.pk %}" method="post">
                                                {% csrf_token %}
                                                <button class="btn btn-danger btn-sm delete-link ml-2" data-tooltip="tooltip" title="Delete">
                                                    <e class="far fa-trash-alt"></e>
                                                </button>
                                               </form>
                                               {% endif %}
                                            </div>
                                           </td>
                                       

                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{% endblock main %}

dashboard/templates/dashboard/products/list.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Category</h1>
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Product</h6>
                        <div class="float-right">
                            <a href="{% url 'dashboard:products-create' %}" class = "btn btn-primary">
                                <i class="fa fa-plus"></i>&nbsp; Add Product
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Name</th>
                                        <th>Selling Price</th>
                                        <th>Cost Price</th>
                                        <th>Quantity Stock</th>
                                        <th>Manufacture Date</th>
                                        <th>Expired Date</th>
                                        <th>Company</th>
                                        <th>Image</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for object in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ object.name }}</td>
                                        <td>{{ object.selling_price }}</td>
                                        <td>{{ object.cost_price }}</td>
                                        <td>{{ object.quantity_stock }}</td>
                                        <td>{{ object.mfg_date }}</td>
                                        <td>{{ object.expired_date }}</td>
                                        <td>{{ object.company }}</td>
                                        <td><img src="{{ object.product_image.url }}" alt="" width="200px"></td>
                                        <td>
                                            <div class="btn-group" role="group">
                                               <a href="{% url 'dashboard:products-update' object.pk %}" class="btn btn-info btn-sm">
                                                <i class="fas fa-pen"></i>
                                               </a> 
                                               {% if not object.non_deletetable %}
                                               <form action="{% url 'dashboard:products-delete' object.pk %}" method="post">
                                                {% csrf_token %}
                                                <button class="btn btn-danger btn-sm delete-link ml-2" data-tooltip="tooltip" title="Delete">
                                                    <e class="far fa-trash-alt"></e>
                                                </button>
                                               </form>
                                               {% endif %}
                                            </div>
                                           </td>
                                       

                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{% endblock main %}